name: release-tag

on:
  push:
    branches:
      - main
    paths:
      - version.txt

jobs:
  tag:
    if: ${{ github.repository == 'llaoj/gcopy' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: /usr/bin/git config --global user.email actions@github.com
      - run: /usr/bin/git config --global user.name 'GitHub Actions Release Tagger'
      - run: hack/release-tag.sh
        id: release_tag
    outputs:
      release_tag: ${{ steps.release_tag.outputs.release_tag }}
